Feature/6 add docker support
OlegMikus/ITechArt-trainee pull request #10
Opened 2021-09-15 14:16 UTC by OlegMikus

2021-09-15 14:24 UTC, ishaurko requested changes

2021-09-15 14:24 UTC, ishaurko commented on Dockerfile
> +COPY . .
copy only src

2021-09-15 14:25 UTC, OlegMikus commented on Dockerfile
> +COPY . .
I also need .env for everything to work

2021-09-15 15:05 UTC, ishaurko requested changes

2021-09-15 15:05 UTC, ishaurko commented on src/models/migrations/README
> +Single-database configuration for Flask.
Pretty unhelpful readme

2021-09-15 15:07 UTC, OlegMikus commented on src/models/migrations/README
> +Single-database configuration for Flask.
I'll remove migrations from this PR

2021-09-15 15:07 UTC, OlegMikus commented on .env
> +DATABASE_HOST=localhost:54322
Ok

2021-09-16 09:54 UTC, ishaurko approved these changes

2021-09-16 09:58 UTC, merged